# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20160121_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='captain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
