# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 21:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, upload_to='event_pics/')),
                ('min_participants', models.IntegerField(default=1)),
                ('is_team_event', models.BooleanField(default=False)),
                ('managers', models.ManyToManyField(related_name='managing', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='participating', to=settings.AUTH_USER_MODEL)),
                ('winners', models.ManyToManyField(related_name='winnings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
